@echo off
color 0a
title Wolf Head

echo ....................................................................................................
echo .....    ...................................................................................    ....
echo ... ^7~^:.     .......................................................................    ..:^~!. ..
echo .....?5YYJ?!~^:.     ..........................................................     ..:^~7?JYY5~ ...
echo .... .J5YY555YYJ?7~^:.     ..............................................     ..:^!7?JYY555YY5! ....
echo ..... :YYYYYYYYY555YYJ?7~^:.                                            ..:^!7?JYY55555YYYYY5?. ....
echo ...... ^YYYYYYYYYYYYYY555YYJ?7~^:::::::::::::::::::::::::::::::::::::^!7?JYY555YY55YY?~7YYY5J. .....
echo ....... !5YYYYYYYYY5YYYYYYYY555YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY555YYYYYY55Y?!^. ~YYYYY: ......
echo ........ 75YYYYYYYY7JYY555YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ7~:.   ~YYYYY~ .......
echo ........ .J5YYYYYYY~ .^~7?JYY55555555555555555555YYYYYYYYYYYYYYYYYYYYYYYYYYJ7!!: .. ^YYYY5! ........
echo ......... :YYYYYYYYJ:     .:^!7777777777777777777JYYYYYYYYYYYYYYYYYYYYYYYYYYY5Y: . ^YYYY5?..........
echo .......... ^YYYYYYY5? .....                      ?5YYYYYYYYYYYYYYYYYYYYYYYYYY5?  .~YYYY5J. .........
echo ........... !YYYYYYYY~ ........................ .YYYYYYYYYYYYYYYYYYYYYYYYYYYY5~ ~J5YYYYY: ..........
echo ............ 75YYYYYYY: ....................... ^YYYYYYYYYYYYYYYYYYYYYYYYYYYYY!J5YYYYYY~ ...........
echo ........... .JYYYYYYY5? ....................... !5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY! ...........
echo .......... .?5YYYYY5YY5~ .......................?5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5! ..........
echo .......... 75YYYYYY?JYYY: .................... .YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY~ .........
echo ......... !5YYYYYY~ ..:^: .................... ^5Y555YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY^ ........
echo ........ ~YYYYYY5!  .    ..................... !YJ?7!YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJ: .......
echo ....... ^YYYYYYY! ................................  .YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5J. ......
echo ...... :YYYYYYY?^!J~ ........................... .. :YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5?. .....
echo ..... .J5YYYYYYYY57 ............................... ^YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY57 .....
echo .... .?5YYYYYYYY5?. ............................... ~5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5! ....
echo .....!YJJYYYYYYYY: ................................ !5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJYY^ ...
echo .....:..?YYYYYYY^ ................................. 75YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY~.......
echo .....  !5YYYYY5! ........     ..................... ?5YYYYYYYYYYYYYYYYY555YYYYYYYYYYYYYYYYYYY^ .....
echo ..... ~YYYYYY5?....... ^?7!^:..      ...............JYYYYYYYYYYY5555YYJ?7~JYYYYYYYYYYYYYYYYYYY: ....
echo .... ^YYYYYYYJ: ....... ~555YYJ?7~^:..     ....... .JYYYYY555YYJ?7!^:..  !YYYYYYYYYYYYYYYYYYY5J. ...
echo ... :YYYYYYYY^ ......... ~YYYYY555YYYJ?!~^:....... :YYYYYJ7!~:..        !5YYYYYYYYYYYYYYYYYYYY5?. ..
echo .. :J5YYYYYYJ:  ......... !YYYYYYYYYYY555YY: ..... ^YYYY57  ...::^^^~~~7YYYYYYYYYYYYYYYYYYYYYYY5?...
echo ...?5YYYYYYYYY!.  ........ !YYYYYYYYYY55YY5~ ..... ~5YYY5! ~YYYYYYYY5555YYYYYYYYYYYYYYYYYYYYYYYY!...
echo ...~J5YYYYYYYY5Y!. ........ ...::::^^^^!YY5! ..... !5YYY5~:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY~ ...
echo ... .7YYYYYYYYYY5J~. .. .7J:            7557 ..... 75YYYY~J5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5J^ ....
echo ....  ^J5YYYYYYYYY5J^. .755J: ......... :J5?...... ?5YYYYJYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5J: .....
echo ...... .7YYYY5YYYYYYY?^75YY5J: ......... ~5J.......?5YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5YY57. ......
echo .......  ^JY~7Y5YYYYY5YYYYYY5J. ......... ?Y: .....JYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5Y~!5!. .......
echo ......... .^  ^J5YYYYYYYYYYYY5J. ........ :Y^ ... .YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5Y7: .^ .........
echo ..........  .. .~Y5YYYYYYYYYYY5?. ........ ~~ ... :YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5J^  .. ..........
echo ................ :7Y5YYYYYYYYYY5?. .........: ... ^YYYYYYYYYYYYYYYYYYYYYY5YYYYYY5Y~. ...............
echo .................  ^?5YYYY5YYYYY5?. ........ .... ~5YYYYYYYYYYYYYYYYYYYYY?YYYY5Y7: .................
echo ................... .~J55?!YYYYYY5?. ............ !5YYYYYYYYYYYYYYYYYYY5?.^Y55?^  ..................
echo ..................... .7?. ~YYYYYY5?. ........... 75YYYYYYYYYYYYYYYYYYYJ.  ^?~. ....................
echo ......................  . . !5YYYYY5?. .......... ?55YYYYYYYYYYYYYYYYYY^ .. . ......................
echo ............................ !5YYYYY57. ...       .~?JYYYYYYYYYYYYYYYY~ ............................
echo ............................. 75YYYYY57. . ^!!!!!!!!!7JYYYYYYYYYYYYY57 .............................
echo ...............................75YYYYY57.  .J55555555YYYYYYYYYYYYYY5?. .............................
echo .............................. .75YYYYY57...~YYYYYYYYYYYYYYYYYYYYYYJ: ..............................
echo ............................... .?5YYYYYYJJYYYYYYYYYYYYYYYYYYYYYYYY^ ...............................
echo ................................ .?555YYYYYYYYYYYYYYYYYYYYYYYYY55Y~ ................................
echo ................................. .^!?YY55YYYYYYYYYYYYYYYYY55YJ?!^..................................
echo...................................  ..^!?JY55YYYYYYYYY55YJ7~:.   ..................................
echo ......................................    .:~7JY5555YY?7~:.   ......................................
echo ...........................................   .:~7?!^:.   ..........................................
echo ...............................................       ..............................................
echo ....................................................................................................
pause >nul